import AppDate from "./date";
const { start } = AppDate.getCurrentMonthDates;

const AppConstant = {
  login: {
    apiPath: "user/auth.php",
    storage: "USER-INFO",
    roles: {
      admin: "admin",
    },
    fields: {
      username: {
        name: "username",
        label: "Username",
        type: "text",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      password: {
        name: "password",
        label: "Password",
        type: "password",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
    },
  },
  admin: {
    apiPath: "read_all.php",
    school: {
      apiPath: {
        create: "school/create.php",
        update: "school/update.php",
        delete: "school/delete.php",
      },
      search: {
        name: "search",
        label: "Search School",
        type: "search",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      fields: {
        name: {
          name: "name",
          label: "School Name",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: false,
          value: "",
        },
        detail: {
          name: "detail",
          label: "School Detail",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: true,
          rows: 4,
          value: "",
        },
      },
    },
    standard: {
      apiPath: {
        create: "standard/create.php",
        update: "standard/update.php",
        delete: "standard/delete.php",
      },
      search: {
        name: "search",
        label: "Search Standard",
        type: "search",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      fields: {
        name: {
          name: "name",
          label: "Standard Name",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: false,
          value: "",
        },
        detail: {
          name: "detail",
          label: "Standard Detail",
          type: "text",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: true,
          rows: 4,
          value: "",
        },
        school: {
          name: "school",
          label: "Select School",
          type: "select",
          helperText: null,
          isDisabled: false,
          isError: false,
          multiline: false,
          value: null,
          options: [],
        },
      },
    },
  },
  expense: {
    apiPath: {
      read: "read.php",
      create: "exp_data/create.php",
      update: "exp_data/update.php",
      delete: "exp_data/delete.php",
    },
    storage: "EXPENSE-INFO",
    fields: {
      date: {
        name: "date",
        label: "Category date",
        type: "date",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: new Date(),
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      amount: {
        name: "amount",
        label: "Expense Amount",
        type: "number",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: "",
      },
      note: {
        name: "note",
        label: "Expense Detail",
        type: "text",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: true,
        rows: 3,
        value: "",
      },
    },
    listFields: {
      date: {
        name: "date",
        label: "Select date",
        type: "date",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        minDate: false,
      },
      user: {
        name: "user",
        label: "Select User",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      isPaid: {
        name: "isPaid",
        label: "Select Paid/Not Paid",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [
          { id: true, name: "Paid" },
          { id: false, name: "Not Paid" },
        ],
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
    },
  },
  report: {
    apiPath: {
      read: "exp_data/read_data_by_date.php",
    },
    storage: "EXPENSE-INFO",
    fields: {
      startDate: {
        name: "startDate",
        label: "Start date",
        type: "startDate",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: start,
      },
      endDate: {
        name: "endDate",
        label: "End date",
        type: "endDate",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: AppDate.getDateIntoString(),
      },
    },
    listFields: {
      user: {
        name: "user",
        label: "Select User",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      isPaid: {
        name: "isPaid",
        label: "Select Paid/Not Paid",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [
          { id: true, name: "Paid" },
          { id: false, name: "Not Paid" },
        ],
      },
      category: {
        name: "category",
        label: "Expense Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
      detail: {
        name: "detail",
        label: "Expense Sub Category",
        type: "select",
        helperText: null,
        isDisabled: false,
        isError: false,
        multiline: false,
        value: null,
        options: [],
      },
    },
  },
};
export default AppConstant;
